#!/bin/sh

set -e

case "$1" in
	purge)
		rm -r /etc/vlmcsd
		;;
	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
		exit 0
		;;
	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 0
		;;
esac

#DEBHELPER#

exit 0
